package com.epam.hospital.util;

import java.util.Locale;
import java.util.ResourceBundle;

public class LabelsHolder {
    public static String RU = "Русский";
    public static String EN = "English";
    public static String SIGNED;
    public static String SIGNOUT;
    public static String NAME;
    public static String SURNAME;
    public static String DOB;
    public static String PREV;
    public static String P_CARD;
    public static String NEXT;
    public static String ADD_P;
    public static String SELECTPATIENT;
    public static String DETAILS;
    public static String DIAGNOSIS;
    public static String DIAGNISEDBY;
    public static String DIAGNOSEDDATE;
    public static String BACKTOTHEPATIENT;
    public static String SAVE;
    public static String APPOINTEDBY;
    public static String FULFILLEDBY;
    public static String APPOINTMENT;
    public static String PATIENT;
    public static String APPDATE;
    public static String FULFULLDATE;
    public static String BACKTOPATIENT;
    public static String NOTFOUND;
    public static String DIAGNOSES;
    public static String APPOINTMENTS;
    public static String USERNAME;
    public static String BIRTHDATE;
    public static String NEWDIAGNOSIS;
    public static String SAVEPATIENT;
    public static String NEWAPPOINT;
    public static String DISCHARGE;
    public static String FULFILL;
    public static String CHANGEDIAGNOSIS;
    public static String CHANGEAPPOINT;
    public static String USERNOTFOUND;
    public static String APPTOCHANGE;
    public static String APPTOFULFILL;
    public static String DIAGNOSISTODISCHARGE;
    public static String ID;
    public static String DIAGNOSISDEATE;
    public static String DIAGNOSEDBY;
    public static String APPOINTMENTTYPE;
    public static String APPOINTMENTDATE;
    public static String FULFILLDATE;
    public static String FULFILLBY;
    public static String INTREATMENT;
    public static String PATIENTNOTFOUND;
    public static String STATUS;
    public static String PATIENTSTAT;

    public static void chageLocale(Locale locale) {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("components", locale);
        SIGNED = resourceBundle.getString("menu.signed.caption");
        SIGNOUT = resourceBundle.getString("menu.signout.button");
        NAME = resourceBundle.getString("patient.list.table.name");
        SURNAME = resourceBundle.getString("patient.list.table.surname");
        DOB = resourceBundle.getString("patient.list.table.birthdate");
        PREV = resourceBundle.getString("patient.list.button.previous");
        P_CARD = resourceBundle.getString("patient.list.button.patientDetails");
        NEXT = resourceBundle.getString("patient.list.button.next");
        ADD_P = resourceBundle.getString("patient.list.button.add");
        SELECTPATIENT = resourceBundle.getString("card.patient.select");
        DETAILS = resourceBundle.getString("card.grid.details");
        DIAGNOSIS = resourceBundle.getString("card.grid.diagnosis");
        DIAGNISEDBY = resourceBundle.getString("card.grid.diagnosisby");
        DIAGNOSEDDATE = resourceBundle.getString("card.grid.diagnosisdate");
        BACKTOTHEPATIENT = resourceBundle.getString("appview.backtopatient");
        SAVE = resourceBundle.getString("appview.save");
        APPOINTEDBY = resourceBundle.getString("card.grid.appointedby");
        FULFILLEDBY = resourceBundle.getString("card.grid.fulfilledby");
        APPOINTMENT = resourceBundle.getString("card.grid.appointment");
        PATIENT = resourceBundle.getString("appview.patient");
        APPDATE = resourceBundle.getString("card.grid.appointmentdate");
        FULFULLDATE = resourceBundle.getString("card.grid.fulfilldate");
        BACKTOPATIENT = resourceBundle.getString("appview.backtopatient");
        NOTFOUND = resourceBundle.getString("card.usernotfound");
        DIAGNOSES = resourceBundle.getString("card.diagnoses");
        APPOINTMENTS = resourceBundle.getString("card.appointments");
        USERNAME = resourceBundle.getString("card.username");
        NAME = resourceBundle.getString("patient.list.table.name");
        SURNAME = resourceBundle.getString("patient.list.table.surname");
        BIRTHDATE = resourceBundle.getString("patient.list.table.birthdate");
        NEWDIAGNOSIS = resourceBundle.getString("card.diagnosis.add.button");
        SAVEPATIENT = resourceBundle.getString("card.patient.save.button");
        NEWAPPOINT = resourceBundle.getString("card.appointment.new.button");
        DISCHARGE = resourceBundle.getString("card.discharge.button");
        FULFILL = resourceBundle.getString("card.fulfill.button");
        CHANGEDIAGNOSIS = resourceBundle.getString("card.diagnosis.change.button");
        CHANGEAPPOINT = resourceBundle.getString("card.appointment.change.button");
        USERNOTFOUND = resourceBundle.getString("card.usernotfound");
        APPTOCHANGE = resourceBundle.getString("card.appointment.tochange");
        APPTOFULFILL = resourceBundle.getString("card.appointment.tofulfill");
        DIAGNOSISTODISCHARGE = resourceBundle.getString("card.diagnosis.todischarge");
        ID = resourceBundle.getString("card.grid.id");
        DIAGNOSISDEATE = resourceBundle.getString("card.grid.diagnosisdate");
        DIAGNOSEDBY = resourceBundle.getString("card.grid.diagnosisby");
        APPOINTMENTTYPE = resourceBundle.getString("card.grid.appointmenttype");
        APPOINTMENTDATE = resourceBundle.getString("card.grid.appointmentdate");
        FULFILLDATE = resourceBundle.getString("card.grid.fulfilldate");
        FULFILLBY = resourceBundle.getString("card.grid.fulfilledby");
        INTREATMENT = resourceBundle.getString("card.intreatment.lable");
        PATIENTNOTFOUND = resourceBundle.getString("card.patient.notfound");
        STATUS = resourceBundle.getString("grid.diagnosis.status");
        PATIENTSTAT = resourceBundle.getString("card.patient.status");
    }
}
